<#
.SYNOPSIS
  Writes this machine an aiusage-update.cmd with its own checkout path in it.

.DESCRIPTION
  Three machines run this project from three different directories and the
  update steps are otherwise identical. Retyping the path is the part that
  actually goes wrong, so it is read from where this script lives rather than
  typed.

  Two files are written next to start-serve.cmd:

    aiusage-update.cmd      the whole update, in order
    aiusage-stop-serve.ps1  the one step cmd.exe cannot express safely

  The order inside the .cmd is the point of the file: pull, build, stop,
  start, read the log. Stopping first leaves the machine with no serve
  for as long as the build takes, and the watchdog fires every five minutes,
  so a build that runs longer than that gets a second serve started on top of
  a half-written dist. That is not hypothetical; it happened on the laptop.

.PARAMETER WithWeb
  Also build the dashboard. Only the hub serves a screen; on a spoke this is
  a minute of build time for something nobody opens. Since serve now warns
  rather than refusing when dist/web is absent, leaving it out is a supported
  way to run.

.EXAMPLE
  # on a spoke
  powershell -ExecutionPolicy Bypass -File scripts\write-update-cmd.ps1

.EXAMPLE
  # on the hub
  powershell -ExecutionPolicy Bypass -File scripts\write-update-cmd.ps1 -WithWeb
#>
[CmdletBinding()]
param(
  [switch] $WithWeb,
  [string] $TaskName = 'aiusage-serve',
  [int]    $Port = 3847
)

$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path.TrimEnd('\')

# The .cmd is written as ASCII, as start-serve.cmd is, because cmd.exe reads
# it in the console code page. A path it cannot represent would fail at run
# time with a message about a missing directory rather than about encoding,
# which is a bad hour to spend.
if (([char[]] $repo | Where-Object { [int] $_ -gt 127 }).Count -gt 0) {
  throw "The checkout path has characters cmd.exe cannot be trusted with: $repo"
}

$dest = Join-Path $env:USERPROFILE '.aiusage'
if (-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }

$buildTargets = if ($WithWeb) {
  '--filter @aiusage/web --filter @aiusage/cli'
} else {
  '--filter @aiusage/cli'
}

$webNote = if ($WithWeb) {
  'rem This machine serves the dashboard, so the web package is built too.'
} else {
  'rem This machine serves no screen, so the web package is not built. serve'
}

$webNote2 = if ($WithWeb) {
  'rem'
} else {
  'rem says so on startup and keeps going; /api is all this machine needs.'
}

$cmd = @"
@echo off
setlocal
rem Generated by scripts\write-update-cmd.ps1 - change that, not this.
rem Checkout: $repo
rem
rem One command, because the starting point was that updating three machines
rem by hand is a chore, and leaving the pull out only answered half of that.
rem
rem It prints where it moved from and to. What is running and what is checked
rem out remain two separate facts - the hub reports the first - and this line
rem is where you can see them line up.
rem
rem The order below is the point of the file. Build first: stopping first
rem would leave this machine without a serve for the length of the build,
rem and the 5-minute watchdog would start a second one on top of a
rem half-written dist.

set "AIUSAGE_REPO=$repo"
set "AIUSAGE_LOG=%USERPROFILE%\.aiusage\serve.log"
set "AIUSAGE_PORT=$Port"
set "AIUSAGE_TASK=$TaskName"

rem --- 1. pull --------------------------------------------------------------
cd /d "%AIUSAGE_REPO%"
if errorlevel 1 (
  echo aiusage-update: no checkout at %AIUSAGE_REPO%
  exit /b 1
)

for /f %%i in ('git rev-parse --short HEAD') do set "AIUSAGE_WAS=%%i"

rem --ff-only: a merge commit made by a script at 2am, on a machine nobody
rem is looking at, is not something anyone wants to discover later.
git pull --ff-only
if errorlevel 1 (
  echo aiusage-update: pull failed - nothing was built or stopped.
  exit /b 1
)

for /f %%i in ('git rev-parse --short HEAD') do set "AIUSAGE_NOW=%%i"

rem Said either way. "Nothing came down" is an answer to the question you
rem ran this to ask, and swallowing it turns a no-op into a silence.
rem
rem Written with goto rather than if/else because a variable set inside a
rem parenthesised block is not readable inside that same block, and the
rem usual workaround for that re-parses the line and eats the arrow.
if "%AIUSAGE_WAS%"=="%AIUSAGE_NOW%" goto :aiusage_same
for /f %%i in ('git rev-list --count %AIUSAGE_WAS%..%AIUSAGE_NOW%') do set "AIUSAGE_N=%%i"
echo Updating: %AIUSAGE_WAS% -^> %AIUSAGE_NOW%   (%AIUSAGE_N% commits)
goto :aiusage_pulled
:aiusage_same
echo Already up to date at %AIUSAGE_NOW%.
:aiusage_pulled

rem --- 2. build -------------------------------------------------------------
$webNote
$webNote2

call pnpm install --frozen-lockfile
if errorlevel 1 (
  echo aiusage-update: install failed - the running serve was left alone.
  exit /b 1
)

call pnpm $buildTargets build
if errorlevel 1 (
  echo aiusage-update: build failed - the running serve was left alone.
  exit /b 1
)

rem --- 3. stop the old one --------------------------------------------------
rem schtasks /End ends the cmd.exe and leaves its node child running, and
rem that child keeps the port, which makes the restart below a silent no-op.
rem So the port has to be taken from whoever holds it - after checking that
rem whoever that is, is ours.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0aiusage-stop-serve.ps1" -Port %AIUSAGE_PORT% -Repo "%AIUSAGE_REPO%"
if errorlevel 1 (
  echo aiusage-update: did not stop the old serve - not starting a second one.
  exit /b 1
)

rem --- 4. start the new one -------------------------------------------------
schtasks /Run /TN "%AIUSAGE_TASK%"
if errorlevel 1 (
  echo aiusage-update: could not run the task. Start it by hand:
  echo   "%USERPROFILE%\.aiusage\start-serve.cmd"
  exit /b 1
)

rem --- 5. say whether it worked ---------------------------------------------
rem Not optional. Every step above can report success while serve exits on
rem startup, and the log is the only place that shows it.
timeout /t 25 /nobreak >nul
powershell -NoProfile -Command "Get-Content -LiteralPath '%AIUSAGE_LOG%' -Tail 16 -Encoding UTF8"
echo.
echo aiusage-update: if the times above are not from just now, the old serve
echo is still running - see docs\project\SETUP-NEW-MACHINE.md.
"@

$stop = @"
<#
  Stops the serve that holds the port, and nothing else.

  Stop-Process -Name node would take every node on the machine with it,
  including whatever the person at the keyboard is running. So: find who
  holds the port, check it is node running this checkout, and only then stop
  it. Anything else holding the port is reported and left alone - killing an
  unknown process to free a port is not this script's business.

  Generated by scripts\write-update-cmd.ps1 - change that, not this.
#>
param(
  [int]    `$Port = $Port,
  [string] `$Repo = '$repo'
)

`$ErrorActionPreference = 'Stop'

`$owners = @(Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty OwningProcess -Unique)

if (`$owners.Count -eq 0) {
  # Not a failure. The machine may have been rebooted, or serve may have
  # exited on its own; either way there is nothing here to stop.
  Write-Host "nothing is listening on `$Port; carrying on"
  exit 0
}

`$stopped = 0
foreach (`$procId in `$owners) {
  `$p = Get-CimInstance Win32_Process -Filter "ProcessId=`$procId" -ErrorAction SilentlyContinue
  if (`$null -eq `$p) { continue }
  if (`$p.Name -eq 'node.exe' -and `$p.CommandLine -and `$p.CommandLine.Contains(`$Repo)) {
    Write-Host "stopping serve (pid `$(`$p.ProcessId))"
    Stop-Process -Id `$p.ProcessId -Force
    `$stopped++
  } else {
    Write-Host "port `$Port is held by `$(`$p.Name) (pid `$(`$p.ProcessId)), which is not this checkout - leaving it alone"
  }
}

if (`$stopped -eq 0) {
  # Starting anyway would find the port taken, retreat to 3848, and write
  # that into .serve-port - which repoints every hook at the new instance
  # while the old one keeps running.
  Write-Host 'the port is held by something else; refusing to start a second serve'
  exit 1
}

Start-Sleep -Seconds 3
exit 0
"@

Set-Content -Path (Join-Path $dest 'aiusage-update.cmd') -Value $cmd -Encoding ascii
Set-Content -Path (Join-Path $dest 'aiusage-stop-serve.ps1') -Value $stop -Encoding ascii

Write-Host "wrote $dest\aiusage-update.cmd"
Write-Host "wrote $dest\aiusage-stop-serve.ps1"
Write-Host "checkout baked in: $repo"
Write-Host "dashboard: $(if ($WithWeb) { 'built' } else { 'not built (spoke)' })"
