<#
.SYNOPSIS
  Writes this machine an aiusage-update.cmd with its own checkout path in it.

.DESCRIPTION
  Three machines run this project from three different directories and the
  update steps are otherwise identical. Retyping the path is the part that
  actually goes wrong, so it is read from where this script lives rather than
  typed.

  Two files are written next to start-serve.cmd:

    aiusage-update.cmd      the whole update, in order
    aiusage-stop-serve.ps1  the one step cmd.exe cannot express safely

  The order inside the .cmd is the point of the file: pull, build, stop,
  start, read the log. Stopping first leaves the machine with no serve
  for as long as the build takes, and the watchdog fires every five minutes,
  so a build that runs longer than that gets a second serve started on top of
  a half-written dist. That is not hypothetical; it happened on the laptop.

.PARAMETER WithWeb
  Also build the dashboard. Only the hub serves a screen; on a spoke this is
  a minute of build time for something nobody opens. Since serve now warns
  rather than refusing when dist/web is absent, leaving it out is a supported
  way to run.

.EXAMPLE
  # on a spoke
  powershell -ExecutionPolicy Bypass -File scripts\write-update-cmd.ps1

.EXAMPLE
  # on the hub
  powershell -ExecutionPolicy Bypass -File scripts\write-update-cmd.ps1 -WithWeb
#>
[CmdletBinding()]
param(
  [switch] $WithWeb,
  [string] $TaskName = 'aiusage-serve',
  [int]    $Port = 3847
)

$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path.TrimEnd('\')

# The .cmd is written as ASCII, as start-serve.cmd is, because cmd.exe reads
# it in the console code page. A path it cannot represent would fail at run
# time with a message about a missing directory rather than about encoding,
# which is a bad hour to spend.
if (([char[]] $repo | Where-Object { [int] $_ -gt 127 }).Count -gt 0) {
  throw "The checkout path has characters cmd.exe cannot be trusted with: $repo"
}

$dest = Join-Path $env:USERPROFILE '.aiusage'
if (-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }

# Read from the workspace, not typed.
#
# The CLI package is not called what the directory is called, and a
# --filter that matches nothing is not an error to pnpm: it prints one
# line and exits 0. The first real run of this script built the dashboard,
# skipped the CLI entirely, restarted serve on the old code and reported
# success. Reading the names removes the chance to be wrong about them.
function Get-PackageName([string] $dir) {
  $file = Join-Path $repo "packages\$dir\package.json"
  if (-not (Test-Path $file)) { throw "no package.json for $dir at $file" }
  $name = (Get-Content $file -Raw | ConvertFrom-Json).name
  if (-not $name) { throw "packages/$dir has no name" }
  return $name
}

$cliPackage = Get-PackageName "cli"
$webPackage = Get-PackageName "web"

$buildTargets = if ($WithWeb) {
  "--filter $webPackage --filter $cliPackage"
} else {
  "--filter $cliPackage"
}

$webNote = if ($WithWeb) {
  'rem This machine serves the dashboard, so the web package is built too.'
} else {
  'rem This machine serves no screen, so the web package is not built. serve'
}

$webNote2 = if ($WithWeb) {
  'rem'
} else {
  'rem says so on startup and keeps going; /api is all this machine needs.'
}

$cmd = @"
@echo off
setlocal
rem Generated by scripts\write-update-cmd.ps1 - change that, not this.
rem Checkout: $repo
rem
rem One command, because the starting point was that updating three machines
rem by hand is a chore, and leaving the pull out only answered half of that.
rem
rem It prints where it moved from and to. What is running and what is checked
rem out remain two separate facts - the hub reports the first - and this line
rem is where you can see them line up.
rem
rem The order below is the point of the file. Build first: stopping first
rem would leave this machine without a serve for the length of the build,
rem and the 5-minute watchdog would start a second one on top of a
rem half-written dist.

set "AIUSAGE_REPO=$repo"
set "AIUSAGE_LOG=%USERPROFILE%\.aiusage\serve.log"
set "AIUSAGE_PORT=$Port"
set "AIUSAGE_TASK=$TaskName"

rem --- 0. nothing below may stop and ask a person ---------------------------
rem This is meant to be one command on a machine nobody is watching. A step
rem that waits for an answer does not fail and does not finish: it produces
rem no outcome at all, which is the one result nothing here can report on.
rem
rem corepack asks before downloading the pnpm version that packageManager
rem pins. Answered in advance rather than routed around, because the pin is
rem what keeps three machines on one pnpm; going around corepack would trade
rem a prompt for a version drift nobody would notice. It still prints what it
rem is downloading.
set "COREPACK_ENABLE_DOWNLOAD_PROMPT=0"
rem
rem And git asks for credentials when the stored ones expire. This stops it
rem asking at the terminal; the credential helper is told not to open a
rem window of its own on the pull itself, below.
set "GIT_TERMINAL_PROMPT=0"

rem --- 1. pull --------------------------------------------------------------
cd /d "%AIUSAGE_REPO%"
if errorlevel 1 (
  echo aiusage-update: no checkout at %AIUSAGE_REPO%
  exit /b 1
)

for /f %%i in ('git rev-parse --short HEAD') do set "AIUSAGE_WAS=%%i"

rem --ff-only: a merge commit made by a script at 2am, on a machine nobody
rem is looking at, is not something anyone wants to discover later.
rem -c credential.interactive=false: the helper on this remote is a GUI one,
rem and a dialog on a machine nobody is looking at is the worst version of
rem this problem - no output, no failure, no end. Better to fail here and
rem have someone run git pull by hand once, where it can ask.
git -c credential.interactive=false pull --ff-only
if errorlevel 1 (
  echo aiusage-update: pull failed - nothing was built or stopped.
  echo If it mentions authentication, the stored credential has expired:
  echo run "git pull" by hand once, where it can ask.
  exit /b 1
)

for /f %%i in ('git rev-parse --short HEAD') do set "AIUSAGE_NOW=%%i"

rem Said either way. "Nothing came down" is an answer to the question you
rem ran this to ask, and swallowing it turns a no-op into a silence.
rem
rem Written with goto rather than if/else because a variable set inside a
rem parenthesised block is not readable inside that same block, and the
rem usual workaround for that re-parses the line and eats the arrow.
if "%AIUSAGE_WAS%"=="%AIUSAGE_NOW%" goto :aiusage_same
for /f %%i in ('git rev-list --count %AIUSAGE_WAS%..%AIUSAGE_NOW%') do set "AIUSAGE_N=%%i"
echo Updating: %AIUSAGE_WAS% -^> %AIUSAGE_NOW%   (%AIUSAGE_N% commits)
goto :aiusage_pulled
:aiusage_same
echo Already up to date at %AIUSAGE_NOW%.
:aiusage_pulled

rem --- 2. build -------------------------------------------------------------
$webNote
$webNote2

rem Compared against 0 rather than tested with "if errorlevel 1", which is
rem true only for codes of 1 or more and quietly passes a negative one.
call pnpm install --frozen-lockfile
if not "%ERRORLEVEL%"=="0" (
  echo aiusage-update: install failed - the running serve was left alone.
  echo If this was EACCES on a linux-x64 path, it is the broken store links:
  echo see docs\project\OPERATIONS.md - the section on pnpm and EACCES.
  exit /b 1
)

call pnpm $buildTargets build
if not "%ERRORLEVEL%"=="0" (
  echo aiusage-update: build failed - the running serve was left alone.
  exit /b 1
)

rem --- 3. stop the old one --------------------------------------------------
rem schtasks /End ends the cmd.exe and leaves its node child running, and
rem that child keeps the port, which makes the restart below a silent no-op.
rem So the port has to be taken from whoever holds it - after checking that
rem whoever that is, is ours.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0aiusage-stop-serve.ps1" -Port %AIUSAGE_PORT% -Repo "%AIUSAGE_REPO%"
if errorlevel 1 (
  echo aiusage-update: did not stop the old serve - not starting a second one.
  exit /b 1
)

rem --- 4. start the new one -------------------------------------------------
rem And says whether it came back, which is the only part anyone cares
rem about. schtasks reports a failure on this path even when the restart
rem works, so its output is held and shown only if the port stays dark.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0aiusage-restart-serve.ps1" -Port %AIUSAGE_PORT% -TaskName "%AIUSAGE_TASK%"

rem --- 5. say whether it worked ---------------------------------------------
rem Not optional. Every step above can report success while serve exits on
rem startup, and the log is the only place that shows it.
rem
rem Waiting for the port rather than for a fixed number of seconds, because
rem the question is whether serve came back, and the exit code of schtasks
rem does not answer it either way.
powershell -NoProfile -Command "Start-Sleep -Seconds 5"
powershell -NoProfile -Command "Get-Content -LiteralPath '%AIUSAGE_LOG%' -Tail 16 -Encoding UTF8"
echo.
echo aiusage-update: if the times above are not from just now, the old serve
echo is still running - see docs\project\SETUP-NEW-MACHINE.md.
"@

$stop = @"
<#
  Stops the serve that holds the port, and nothing else.

  Stop-Process -Name node would take every node on the machine with it,
  including whatever the person at the keyboard is running. So: find who
  holds the port, check it is node running this checkout, and only then stop
  it. Anything else holding the port is reported and left alone - killing an
  unknown process to free a port is not this script's business.

  Generated by scripts\write-update-cmd.ps1 - change that, not this.
#>
param(
  [int]    `$Port = $Port,
  [string] `$Repo = '$repo'
)

`$ErrorActionPreference = 'Stop'

`$owners = @(Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty OwningProcess -Unique)

if (`$owners.Count -eq 0) {
  # Not a failure. The machine may have been rebooted, or serve may have
  # exited on its own; either way there is nothing here to stop.
  Write-Host "nothing is listening on `$Port; carrying on"
  exit 0
}

`$stopped = 0
foreach (`$procId in `$owners) {
  `$p = Get-CimInstance Win32_Process -Filter "ProcessId=`$procId" -ErrorAction SilentlyContinue
  if (`$null -eq `$p) { continue }
  if (`$p.Name -eq 'node.exe' -and `$p.CommandLine -and `$p.CommandLine.Contains(`$Repo)) {
    Write-Host "stopping serve (pid `$(`$p.ProcessId))"
    Stop-Process -Id `$p.ProcessId -Force
    `$stopped++
  } else {
    Write-Host "port `$Port is held by `$(`$p.Name) (pid `$(`$p.ProcessId)), which is not this checkout - leaving it alone"
  }
}

if (`$stopped -eq 0) {
  # Starting anyway would find the port taken, retreat to 3848, and write
  # that into .serve-port - which repoints every hook at the new instance
  # while the old one keeps running.
  Write-Host 'the port is held by something else; refusing to start a second serve'
  exit 1
}

# Waited on rather than assumed. A killed process can hold its listening
# socket for a moment afterwards, and the caller decides that serve came
# back by seeing something listening again - which the corpse satisfies.
`$w = 0
while (`$w -lt 20 -and (Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue)) {
  Start-Sleep -Seconds 2
  `$w += 2
}

if (Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue) {
  Write-Host "the port is still held `$w seconds after stopping serve"
  exit 1
}

exit 0
"@

$restart = @"
<#
  Starts serve again, and reports on whether it is listening rather than
  on what schtasks said.

  schtasks /Run prints a failure on this path even when the restart works -
  the task has just been ended and is between states - and an error line on
  a successful run is worse than no line at all: it is the one you learn to
  read past. Its output is kept and shown only if the port stays dark, when
  it is the first thing you would want.

  Generated by scripts\write-update-cmd.ps1 - change that, not this.
#>
param(
  [int]    `$Port = $Port,
  [string] `$TaskName = "$TaskName"
)

# /End only when there is something to end. On a task that is already
# Ready it reports a failure of its own.
if ((Get-ScheduledTask -TaskName `$TaskName).State -eq "Running") {
  schtasks /End /TN `$TaskName 2>&1 | Out-Null
}

`$w = 0
while ((Get-ScheduledTask -TaskName `$TaskName).State -eq "Running" -and `$w -lt 30) {
  Start-Sleep -Seconds 2
  `$w += 2
}

`$said = schtasks /Run /TN `$TaskName 2>&1 | Out-String

`$w = 0
while (`$w -lt 90 -and -not (Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue)) {
  Start-Sleep -Seconds 3
  `$w += 3
}

if (Get-NetTCPConnection -LocalPort `$Port -State Listen -ErrorAction SilentlyContinue) {
  Write-Host "aiusage-update: serve is listening on `$Port again after `$w seconds"
  # A few more, so the log tail that follows has the startup lines in it.
  Start-Sleep -Seconds 5
  exit 0
}

Write-Host "aiusage-update: nothing is listening on `$Port `$w seconds after the restart"
Write-Host "what schtasks said:"
Write-Host `$said
exit 1
"@

Set-Content -Path (Join-Path $dest 'aiusage-update.cmd') -Value $cmd -Encoding ascii
Set-Content -Path (Join-Path $dest 'aiusage-stop-serve.ps1') -Value $stop -Encoding ascii
Set-Content -Path (Join-Path $dest 'aiusage-restart-serve.ps1') -Value $restart -Encoding ascii

Write-Host "wrote $dest\aiusage-update.cmd"
Write-Host "wrote $dest\aiusage-stop-serve.ps1"
Write-Host "wrote $dest\aiusage-restart-serve.ps1"
Write-Host "checkout baked in: $repo"
Write-Host "dashboard: $(if ($WithWeb) { 'built' } else { 'not built (spoke)' })"
